module:
  hugoVersion:
    min: 0.73.0
  _merge: "deep"
  imports:
    - path: github.com/google/docsy
      disable: false
    - path: github.com/google/docsy/dependencies
      disable: false
  # mounts:
  #   - source: assets
  #     target: assets
  #   - source: layouts
  #     target: layouts
  #   - source: content
  #     target: content
  #   - source: static
  #     target: static
